// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDURIK6sc7jJ9dVfSVtzDArMoXu92u9iLo',
    appId: '1:82498062553:android:439a482ad129eefd1f56c8',
    messagingSenderId: '82498062553',
    projectId: 'boringapp-20c67',
    storageBucket: 'boringapp-20c67.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9PQWsxAIMBC4qzjBEbMereG4nh6cWwhQ',
    appId: '1:82498062553:ios:0c2b86a0354858c51f56c8',
    messagingSenderId: '82498062553',
    projectId: 'boringapp-20c67',
    storageBucket: 'boringapp-20c67.appspot.com',
    iosClientId:
        '82498062553-cs5m6hncfo0pri3r8k47iglldjh0u360.apps.googleusercontent.com',
    iosBundleId: 'com.filiptuzimek.boringApp',
  );
}
